SELECT *
INTO rdowner.V_ACTIVITY
FROM [dbname].rdowner.V_ACTIVITY
WHERE 1 = 0

SELECT *
INTO rdowner.V_ACTIVITY_DATETIME
FROM [dbname].rdowner.V_ACTIVITY_DATETIME
WHERE 1 = 0

SELECT *
INTO rdowner.V_GROUP
FROM [dbname].rdowner.V_GROUP
WHERE 1 = 0

SELECT *
INTO rdowner.V_ACTIVITYTYPE
FROM [dbname].rdowner.V_ACTIVITYTYPE
WHERE 1 = 0

SELECT *
INTO rdowner.V_DEPARTMENT
FROM [dbname].rdowner.V_DEPARTMENT
WHERE 1 = 0

SELECT *
INTO rdowner.V_EQUIPMENT
FROM [dbname].rdowner.V_EQUIPMENT
WHERE 1 = 0

SELECT *
INTO rdowner.V_LOCATION
FROM [dbname].rdowner.V_LOCATION
WHERE 1 = 0

SELECT *
INTO rdowner.V_LOCATIONGROUP
FROM [dbname].rdowner.V_LOCATIONGROUP
WHERE 1 = 0

SELECT *
INTO rdowner.V_MODULE
FROM [dbname].rdowner.V_MODULE
WHERE 1 = 0

SELECT *
INTO rdowner.V_NAMEDAVAILABILITY
FROM [dbname].rdowner.V_NAMEDAVAILABILITY
WHERE 1 = 0

SELECT *
INTO rdowner.V_POS
FROM [dbname].rdowner.V_POS
WHERE 1 = 0

SELECT *
INTO rdowner.V_SECTION
FROM [dbname].rdowner.V_SECTION
WHERE 1 = 0

SELECT *
INTO rdowner.V_STAFF
FROM [dbname].rdowner.V_STAFF
WHERE 1 = 0

SELECT *
INTO rdowner.V_STUDENT
FROM [dbname].rdowner.V_STUDENT
WHERE 1 = 0

SELECT *
INTO rdowner.V_STUDENTSET
FROM [dbname].rdowner.V_STUDENTSET
WHERE 1 = 0

SELECT *
INTO rdowner.V_SUITABILITY
FROM [dbname].rdowner.V_SUITABILITY
WHERE 1 = 0

SELECT *
INTO rdowner.V_GLOBAL
FROM [dbname].rdowner.V_GLOBAL
WHERE 1 = 0

SELECT *
INTO rdowner.V_TAG
FROM [dbname].rdowner.V_TAG
WHERE 1 = 0

SELECT *
INTO rdowner.V_WEEK_LABEL
FROM [dbname].rdowner.V_WEEK_LABEL
WHERE 1 = 0

SELECT *
INTO rdowner.V_ZONES
FROM [dbname].rdowner.V_ZONES
WHERE 1 = 0

SELECT *
INTO rdowner.V_TAG_RELATION
FROM [dbname].rdowner.V_TAG_RELATION
WHERE 1 = 0

SELECT *
INTO rdowner.V_GROUP_RELATION
FROM [dbname].rdowner.V_GROUP_RELATION
WHERE 1 = 0

SELECT *
INTO rdowner.V_ACTIVITY_STUDENTSET
FROM [dbname].rdowner.V_ACTIVITY_STUDENTSET
WHERE 1 = 0

SELECT *
INTO rdowner.V_STUDENTSET_MODULE
FROM [dbname].rdowner.V_STUDENTSET_MODULE
WHERE 1 = 0

SELECT *
INTO rdowner.V_STUDENT_STUDENTSET
FROM [dbname].rdowner.V_STUDENT_STUDENTSET
WHERE 1 = 0

SELECT *
INTO rdowner.V_AVOID_CONCURRENCY
FROM [dbname].rdowner.V_AVOID_CONCURRENCY
WHERE 1 = 0

SELECT *
INTO rdowner.V_ACTIVITY_EQUIPMENT
FROM [dbname].rdowner.V_ACTIVITY_EQUIPMENT
WHERE 1 = 0

SELECT *
INTO rdowner.V_ACTIVITY_LOCATION
FROM [dbname].rdowner.V_ACTIVITY_LOCATION
WHERE 1 = 0

SELECT *
INTO rdowner.V_ACTIVITY_STAFF
FROM [dbname].rdowner.V_ACTIVITY_STAFF
WHERE 1 = 0

SELECT *
INTO rdowner.V_ACTIVITY_PARENTS
FROM [dbname].rdowner.V_ACTIVITY_PARENTS
WHERE 1 = 0

SELECT *
INTO rdowner.V_ACTIVITY_SECTION
FROM [dbname].rdowner.V_ACTIVITY_SECTION
WHERE 1 = 0

SELECT *
INTO rdowner.V_LOCATION_SUITABILITY
FROM [dbname].rdowner.V_LOCATION_SUITABILITY
WHERE 1 = 0

SELECT *
INTO rdowner.V_POS_MODULE
FROM [dbname].rdowner.V_POS_MODULE
WHERE 1 = 0

SELECT *
INTO rdowner.V_LOCATION_LOCATIONGROUP
FROM [dbname].rdowner.V_LOCATION_LOCATIONGROUP
WHERE 1 = 0

